### ISSUE TITLE
I'd love to help - please commit the source!

### ISSUE THREAD

**Issue by alexbartlow** [blavek/Fallout-4-Character-Builder#1]
Hey, I'd love to play with making some changes to it and doing some tweaks - any chance you could commit the source code, not just the minified stuff?

Thanks!

-Alex

**Comment by blavek** [comment]
Yeah I burned myself with them minified stuff lol because original source was at work and I added the specific perks and lol...

FYI I didn't comment it like at all and I came up with a better way to display the levels right now the loop is a bit laborious

**Comment by blavek** [comment]
I committed the non min source code to the GHPages branch

**Comment by blavek** [comment]
although, it seems to not be working...
